### ISSUE TITLE
list items doesn't appear after fetching

### ISSUE THREAD

**Issue by strawoo** [yardnsm/tmux-1password#1]
Hi there. I set up this plugin. Although signin 1password  account, list items doesn't appear.

**Comment by yardnsm** [comment]
Sorry for the late response, for some reason I did not receive notifications for this repo.

When you're initiating the plugin for the second time (after you've signed in), does the plugin asks you for your master password again? Also, are you getting an error message in the status bar? Make sure to have all the [requirements](https://github.com/yardnsm/tmux-1password#requirements) installed and available in `$PATH`.

Try playing with 1Password CLI, to make sure its working properly on your machine. For example:

```console
$ eval $(op signin my)
$ op list items
```

If you're getting errors or having issues, it could be some issue with the 1Password CLI itself.

**Comment by The33Coder** [comment]
I have same problem. I install all requirements 1Password CLI, fzf and jq.
If I press C-u, 1password ask my password but after I don't have any items.

<img width="232" alt="screenshot 2018-12-24 at 20 48 50" src="https://user-images.githubusercontent.com/12548652/50406012-64087500-07bd-11e9-9268-9c9a9e5492bb.png">

If I try to list items with `op list items`, I see my items.

**Comment by bmdepesa** [comment]
@The33Coder I ran into this problem and solved it by editing the JQ filter in `scripts/main.sh`. 

Where you see: 
```
  local -r JQ_FILTER="
    .[]
    | [select(.overview.URLs | map(select(.u == \"sudolikeaboss://local\")) | length == 1)?]
    | map([ .overview.title, .uuid ]
    | join(\",\"))
    | .[]
  "
```

Change `sudolikeaboss://local\` to `https://my.1password.com`, if you're using a personal account. After this I was able to retrieve my items.

**Comment by The33Coder** [comment]
@bmdepesa I change it `sudolikeaboss://local\` with `https://my.1password.com\` and is little better ! 

<img width="299" alt="screenshot 2019-02-07 at 21 49 22" src="https://user-images.githubusercontent.com/12548652/52442222-e73e1a00-2b22-11e9-9a10-9bc8badb74bf.png">

**Comment by bmdepesa** [comment]
@The33Coder I noticed after posting this that I do not see all items either. My output is the same as yours. Fetching my master credentials works fine. I suspect there was an update to the json schema, but haven't yet delved in to resolve it. If I do, I will post a note here.

**Comment by yardnsm** [comment]
Well, as I wanted to avoid bloating the list with all of the login items, I've used the same technique as the [`sudolikeaboss`](https://github.com/ravenac95/sudolikeaboss) project: only items with URLs of `sudolikeaboss://local` will be shown. Refer to the [README](https://github.com/yardnsm/tmux-1password#configuring-login-items-in-1password) for more details.

However, I think it would be nice to have an option to disable this behaviour. What do you think?

**Comment by bmdepesa** [comment]
@yardnsm Wow thanks. I can't believe I skipped over the relevant section in the readme. I see now why the 1Password credential was the only one displaying.

+1 to having a flag to disable the default behavior, I agree choosing a specific vault would be the best. I plan on using this to store credentials for different cloud providers, so being able to separate those without having to add a website tag would work best for me.

@The33Coder sorry for the misinformation -- I'm going to revert my changes :)

**Comment by The33Coder** [comment]
@yardnsm Ok, but that is supposed to install sudolikeboss and in Requirements, sudolikeboss is not mentioned and in the readme is writing "maintain compatibility with sudolikeaboss"

**Comment by CharlesConner** [comment]
I'm on Linux so none of my urls contains sudolikeaboss, I therefor just switched the 1 in main.sh to a 0:

``` 
 local -r JQ_FILTER="
    .[]
    | [select(.overview.URLs | map(select(.u == \"sudolikeaboss://local\")) | length == 0)?]
    | map([ .overview.title, .uuid ]
    | join(\",\"))
    | .[]
  "
```

**Comment by yardnsm** [comment]
@The33Coder the requirements does not mention `sudolikeaboss` because it's not needed - the URL thingy is being used in order to list only specific items that you explicitly chosen to, *and* in order to maintain compatibility with `sudolikeaboss`. The latter means that if you *happen to have* `sudolikeaboss`, it'll still be working as expected and if you've migrated from `sudolikeaboss` you'll still have the expected behaviour.

**Comment by jaepetto** [comment]
Hi,

I tried the same *fix* as @bmdepesa but I still get an empty list in the pane:
![image](https://user-images.githubusercontent.com/2668031/71485985-3f9e0900-2814-11ea-8ddc-958d55f38022.png)

What could be a permanent fix?

**Comment by odelucca** [comment]
I've the same issue here too. No items are being shown

**Comment by yardnsm** [comment]
Making this plugin compatible with `sudolikeaboss` made it more complicated to setup. As a result, the compatibility with it was removed and all of the items should be fetched by default (as of #18).

If any of you would like to keep the compatibility with `sudolikeaboss`, refer to the [Filtering by custom url](https://github.com/yardnsm/tmux-1password#filtering-by-custom-url) section.
