### ISSUE TITLE
Fetching only logins, not passwords

### ISSUE THREAD

**Issue by odelucca** [yardnsm/tmux-1password#15]
Hi!

I use 1Password to store SSH and GPG keys passwords too. I'm loving the tool, but it is currently only fetching login on websites.

There is any config I should activate to fetch passwords (those items where you store only the password, without any website and login associated to it) too?

**Comment by yardnsm** [comment]
Werid... https://github.com/yardnsm/tmux-1password/commit/0577d827c48e663dd878608a3c7f32d48c7e3d28 should've handle these cases. What `op` version are you using?

**Comment by odelucca** [comment]
The latest version. I've figured out what is going on. The filter is getting only items with URL. Passwords only don't have an URL.

I'm working on a possible solution and I'm going to submit a PR in the near future. I think we should allow users to define their own filter.

**Comment by odelucca** [comment]
The PR #13 fix this issue. Please merge it to master as soon as possible :D
