### ISSUE TITLE
Return one-time password instead of the password

### ISSUE THREAD

**Issue by rjcoelho** [yardnsm/tmux-1password#20]
Maybe with a new key binding .. uppercase 'U' ?

**Comment by yardnsm** [comment]
I'm totally up for it! There is another lovely plugin that uses FZF's keybindings to enable the user to perform more actions that just "copy" the password: https://github.com/rafi/tmux-pass.

Maybe smth like `Ctrl-U` when you're hovering the item in the list. WDYT?
