### ISSUE TITLE
add support to copy to clipboard when selecting the item

### ISSUE THREAD

**Issue by nubunto** [yardnsm/tmux-1password#33]
just started using this, it looks great! it would be nice to be able to copy passwords to clipboard or have it be `send-keys` on selection instead of globally!

**Comment by yardnsm** [comment]
Thanks for the feedback! The plugin already support this king of behaviour, using the following config:

```tmux
set -g @1password-copy-to-clipboard 'on'
```

For more info refer to [the README](https://github.com/yardnsm/tmux-1password?tab=readme-ov-file#copy-the-password-to-clipboard).
