### ISSUE TITLE
Add debug mode

### ISSUE THREAD

**Issue by yardnsm** [yardnsm/tmux-1password#5]
The idea is to have a configuration variable, for example: `@1password-debug`, that when set to `'on'`, the plugin will:

- Add some extra logging on events.
- Does not exit immediately when an error is thrown.

**Comment by BlueDrink9** [comment]
If you're after ideas, a [branch in my fork](https://github.com/BlueDrink9/tmux-passwords/tree/debug) has a way to solve this problem.

Annoyingly, because stdout gets captured, getting debug output is tricky. I used a disable-able stderr.
