### ISSUE TITLE
Would you be ok with a fork for lastpass?

### ISSUE THREAD

**Issue by BlueDrink9** [yardnsm/tmux-1password#7]
I may not get around to it, but I love the look and idea of this plugin, and it doesn't look too difficult to port to use lastpass instead of onepass. May even be possible to create a generic version that just needs commands plugged in!

Would you be happy with this being done?

**Comment by yardnsm** [comment]
Yeah, that sounds awesome! I've also been think of adding support for another client called `1pass`, so the idea of having some generic version makes sense (https://github.com/yardnsm/tmux-1password/issues/6).

**Comment by BlueDrink9** [comment]
I noticed that, which was why I suggested it. Have variables for the actual commands, etc.
